services:

  postgres:
    image: postgres:16
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demo_cicd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: satoru2001/demo-cicd:latest
    container_name: demo-cicd
    depends_on:
      - postgres
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/demo_cicd
      PGUSER: postgres
      PGPASSWORD: postgres
      DATABASE_DRIVER_CLASS_NAME: org.postgresql.Driver
      JPA_DATABASE_PLATFORM: org.hibernate.dialect.PostgreSQLDialect
    ports:
      - "8080:8080"