services:

  postgres:
    image: postgres:16
    container_name: demo-postgres
    environment:
      POSTGRES_DB: demo_cicd
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  app:
    image: satoru2001/demo-cicd:latest
    container_name: demo-cicd
    depends_on:
      - postgres
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: demo_cicd
      PGUSER: postgres
      PGPASSWORD: postgres
    ports:
      - "8080:8080"